#
# sys_localdev.yml
#

- hosts: localdev
  connection: local
  become: yes
  roles:
   - common
   - { role: common_hosts, when: "ansible_distribution == 'Amazon'" }
   - system_user
   - common_td-agent
   - common_java
   - common_maven3
   - common_httpd
   - common_postgresql

