env: localdev
app_username: "app"
app_groupname: "app"
app_deploy_target: "master"

postgresql_data_dir: /var/lib/pgsql/data
postgresql_localnetwork: 192.168.255.0/24
postgresql_encoding: UTF-8
postgresql_locale: ja_JP.UTF-8

