#
# Setting up the Supervisord for Amazon Linux
#

#- name: install supervisor 1/2
#  yum: name=pip state=present enablerepo=epel
#- name: install supervisor
#  yum: name=supervisor state=present enablerepo=epel
#- name: set python's version into 2.6
#  shell: alternatives --set python /usr/bin/python2.6
- name: install supervisor 1/2
  shell: pip-2.7 install supervisor
- name: install supervisor 2/2
  copy: dest=/etc/init.d/supervisor src=initd_supervisor owner=root group=root mode=755

- name: create a directory which stores the "app_supervisor_script"
  file: path=/srv/supervisor/bin state=directory recurse=yes owner=root group=root mode=755
- name: create a directory which stores logs for apps
  file: path=/var/log/{{app_repository_name}} state=directory recurse=yes owner={{app_username}} group={{app_username}} mode=755

- name: create a directory which stores config files
  file: path=/etc/supervisord.d state=directory owner=root group=root mode=755
- name: create the "supervisord.conf" file
  copy: dest=/etc/supervisord.conf src=supervisord_conf owner=root group=root mode=755

- name: write the supervisord config file
  template: src=ini.j2 dest=/etc/supervisord.d/{{app_name}}.ini
#  notify: restart supervisor service
- name: create the init script
  template:  src=script.sh.j2 dest=/srv/supervisor/bin/{{app_name}}.sh owner=root group=root mode=755
#  notify: restart supervisor service

- name: stop supervisor service
  service: name=supervisor state=stopped enabled=yes
- name: sleep 10 seconds
  pause: seconds=10
- name: start supervisor service
  service: name=supervisor state=started enabled=yes
