
- name: Check whether the repository of the Treasure Data CLI exists.
  stat: path=/etc/yum.repos.d/td.repo
  register: check_repository
- name: Install the repository of the the Treasure Data CLI
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh
  when: check_repository.stat.exists == False
- name: Install td-agent
  yum: name=td-agent state=present update_cache=yes

