Vagrant.configure("2") do |config|
  config.vm.box = "Yojimbo108/AmazonLinux2"
 
  config.vm.provider "hyperv" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define :"stdsv4" do |c1|
    c1.vm.hostname = "stdsv4"
    # c1.vm.network "private_network", mac: "001553142516"
    c1.vm.network "private_network", mac: "00155d142516"
  end

end

