#
# common_gradle4
#

- name: Check whether Gradle is installed.
  stat: path={{gradle_home}}/bin/gradle
  register: _check_installed

- name: Install Gradle.
  include: setup-Gradle.yml
  when: _check_installed.stat.exists == false

