# Install Gradle4

- name: Create a temporary file.
  tempfile: state=file prefix=gradledist suffix=.bin
  register: _tmpfile

- name: Download a Gradle distribution file.
  get_url: force=yes url="https://services.gradle.org/distributions/gradle-4.9-bin.zip" dest={{_tmpfile.path}}

- name: Unpacking an archived file.
  unarchive: copy=no src={{_tmpfile.path}} dest={{opt_dir}} owner=root group=root

- name: Adjust permissions and owner of the \"{{gradle_home_original}}\" directory.
  file: state=directory path={{gradle_home_original}} owner=root group=root mode=755

- name: Configuring Gradle4
  file: src={{gradle_home_original}} dest={{gradle_home}} state=link

- name: Installing Gradle environment configuragtion
  copy: src=gradle.sh dest=/etc/profile.d/gradle.sh mode=755 owner=root group=root

- name: Clean up
  file: state=absent path={{_tmpfile.path}}

