#
# common role
#
- name: Install necessary packages.
  yum: name={{item}} update_cache=yes
  with_items:
   - git
   - jq
   - python-pip

- name: Install auto completion configuration for AWS CLI
  copy: src=aws-cli-bash.sh dest=/etc/profile.d/aws-cli-bash.sh mode=755 owner=root group=root

