#
# sys_local.yml
#

- hosts: local
  connection: local
  become: yes
  roles:
  - user_passwd_vagrant
  - common
  - common_httpd
  - common_java
  - common_gradle4
  - common_docker
  - common_postgresql12
  - os_users
  - sys_local

