
- name: Check whether the repository of the Maven exists.
  stat: path=/etc/yum.repos.d/epel-apache-maven.repo
  register: check_repository
- name: Install the repository of the Maven. 1/2
  get_url: url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo dest=/etc/yum.repos.d/epel-apache-maven.repo mode=0644
  when: check_repository.stat.exists == False
- name: Install the repository of the Maven. 2/2
  replace: dest=/etc/yum.repos.d/epel-apache-maven.repo regexp='\$releasever' replace='6'
  when: check_repository.stat.exists == False
- name: Install Maven3
  yum: name=apache-maven state=present update_cache=yes

