
- name: Configure packages' name for AmazonLinux
  include_vars: vars-AmazonLinux.yml
  when: (ansible_distribution == "Amazon")

- name: Configure packages' name for CentOS7
  include_vars: vars-CentOS7.yml
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Install Apache2.4
  yum: name="{{httpd_package_name}}" state=present update_cache=yes

- name: Install Apache2 mod_nss (This can be enabled on CentOS7, because AmazonLinux does not provide it with Apache 2.4)
  yum: name=mod_nss state=present update_cache=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Make Apache2.4 running on boot
  service: name=httpd enabled=yes
  notify: restart httpd service

